baseURL = 'https://eva.tatarka.me/blog'
languageCode = 'en-us'
title = 'evant'
theme = 'PaperMod'

googleAnalytics = 'G-MJ6E9W7J4X'

[params]
author = 'Eva Tatarka'

[params.label]
icon = 'logo.png'

[params.homeInfoParams]
Title = 'blog'
Content = 'Opinions expressed here are my own, not those of my company.'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/evant/'
[[params.socialIcons]]
name = 'rss'
url = 'index.xml'
[[params.socialIcons]]
name = 'mastodon'
url = 'https://pony.social/web/@pixellight'

[params.analytics.google]
SiteVerificationTag = "UA-160017120-1"

[module]
[[module.imports]]
path = "github.com/rootwork/hugo-module-gallery-grid"
