baseURL = 'https://evan.tatarka.me/blog'
languageCode = 'en-us'
title = 'evant'
theme = 'PaperMod'

[params]
author = 'Evan Tatarka'

[params.label]
icon = 'logo.png'

[params.homeInfoParams]
Title = 'blog'
Content = 'Opinions expressed here are my own, not those of my company.'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/evant/'
